version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    env_file:
     - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - './.docker/mongo/data/db:/data/db'
      - ./conf/mongo/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    depends_on:
      - mongo

  grpc-atlant:
    build: .
    env_file:
     - .env
    depends_on:
      - mongo
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grpc-atlant
    ports:
      - ${PORT}:1000